# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 05:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('CategoryId', models.AutoField(primary_key=True, serialize=False)),
                ('CategoryName', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('OrderId', models.AutoField(primary_key=True, serialize=False)),
                ('OrderCreatedTime', models.DateTimeField(auto_now_add=True)),
                ('PaymentTaka', models.FloatField(default=0.0)),
                ('Due', models.FloatField(default=0.0)),
                ('IsSale', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('ProductId', models.AutoField(primary_key=True, serialize=False)),
                ('ProductName', models.CharField(default='', max_length=200)),
                ('ProductUnitPrice', models.FloatField(default=0)),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aarong.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('RouteId', models.AutoField(primary_key=True, serialize=False)),
                ('RouteName', models.CharField(default='', max_length=200)),
                ('RouteLat', models.FloatField(default=0.0)),
                ('RouteLng', models.FloatField(default=0.0)),
                ('User', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('SaleId', models.AutoField(primary_key=True, serialize=False)),
                ('productId', models.IntegerField()),
                ('productName', models.CharField(default='', max_length=200)),
                ('saleQuantity', models.IntegerField(default=0)),
                ('Order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aarong.Order')),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('ShopId', models.AutoField(primary_key=True, serialize=False)),
                ('ShopLat', models.FloatField(default=0.0)),
                ('ShopLng', models.FloatField(default=0.0)),
                ('ShopProviderName', models.CharField(default='', max_length=200)),
                ('ShopAddress', models.CharField(default='', max_length=200)),
                ('ShopCreatedTime', models.DateTimeField(auto_now_add=True)),
                ('Route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aarong.Route')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='Shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aarong.Shop'),
        ),
        migrations.AddField(
            model_name='order',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
