# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 05:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aarong', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='productId',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='productName',
        ),
        migrations.AddField(
            model_name='sale',
            name='Product',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='aarong.Product'),
        ),
        migrations.AddField(
            model_name='sale',
            name='saleMoney',
            field=models.FloatField(default=0.0),
        ),
    ]
