# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-10 07:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aarong', '0002_auto_20170829_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ProductPhoto',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
