# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-10 07:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aarong', '0003_product_productphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='ShopPhoto',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
