# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-10 07:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aarong', '0004_shop_shopphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='CategoryPhoto',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
