# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-11 11:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aarong', '0006_auto_20170910_1625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='IsSale',
        ),
    ]
