# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-20 07:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aarong', '0007_remove_order_issale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='Shop',
        ),
        migrations.RemoveField(
            model_name='order',
            name='User',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='Order',
        ),
        migrations.AddField(
            model_name='sale',
            name='OrderCreatedTime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sale',
            name='PaymentTaka',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='sale',
            name='Shop',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='aarong.Shop'),
        ),
        migrations.AddField(
            model_name='sale',
            name='User',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
