# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-21 04:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aarong', '0008_auto_20170920_1350'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleProductList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('saleQuantity', models.IntegerField(default=0)),
                ('saleMoney', models.FloatField(default=0.0)),
                ('Product', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='aarong.Product')),
            ],
        ),
        migrations.RenameField(
            model_name='sale',
            old_name='PaymentTaka',
            new_name='Total',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='Product',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='saleMoney',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='saleQuantity',
        ),
        migrations.AddField(
            model_name='saleproductlist',
            name='Sale',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='aarong.Sale'),
        ),
    ]
