# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 12:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aarong', '0010_auto_20170921_1144'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherVendor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OtherVendorSale',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('CreatedTime', models.DateTimeField(auto_now_add=True)),
                ('Total', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='OtherVendorSaleProduct',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('saleQuantity', models.IntegerField(default=0)),
                ('saleMoney', models.FloatField(default=0.0)),
                ('OtherVendorSale', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='aarong.OtherVendorSale')),
                ('Product', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='aarong.Product')),
            ],
        ),
    ]
