# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 13:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('aarong', '0012_auto_20171001_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='othervendorsaleproduct',
            name='VendorName',
            field=models.ForeignKey(default="", on_delete=django.db.models.deletion.CASCADE, to='aarong.OtherVendor'),
            preserve_default=False,
        ),
    ]
