# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 13:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aarong', '0013_othervendorsaleproduct_vendorname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='othervendorsaleproduct',
            name='VendorName',
        ),
    ]
