# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 13:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aarong', '0014_remove_othervendorsaleproduct_vendorname'),
    ]

    operations = [
        migrations.AddField(
            model_name='othervendorsaleproduct',
            name='VendorName',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='aarong.OtherVendor'),
            preserve_default=False,
        ),
    ]
