# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aarong', '0015_othervendorsaleproduct_vendorname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField(default='')),
                ('text', models.TextField(default='')),
            ],
        ),
    ]
