# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 13:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('aarong', '0016_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='CreatedTime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
