# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-11 08:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aarong', '0017_notification_createdtime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='othervendorsaleproduct',
            old_name='saleQuantity',
            new_name='Unit',
        ),
        migrations.RemoveField(
            model_name='othervendorsaleproduct',
            name='Product',
        ),
        migrations.AddField(
            model_name='othervendorsaleproduct',
            name='Category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='aarong.Category'),
        ),
    ]
