# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-11 08:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aarong', '0018_auto_20171011_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='othervendorsaleproduct',
            name='Category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aarong.Category'),
        ),
    ]
