# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-11 08:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('aarong', '0019_auto_20171011_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='othervendorsaleproduct',
            name='CreatedTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
