# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-11 08:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('aarong', '0020_auto_20171011_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='othervendorsaleproduct',
            name='CreatedTime',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
