# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-11 08:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aarong', '0018_appuser'),
        ('aarong', '0021_auto_20171011_1432'),
    ]

    operations = [
    ]
