# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-11 21:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aarong', '0023_auto_20171012_0305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='othervendorsaleproduct',
            name='VendorName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aarong.OtherVendor'),
        ),
    ]
