# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-12 01:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aarong', '0026_nicecolor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='othervendorsaleproduct',
            name='Category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_name', to='aarong.Category'),
        ),
    ]
