# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-24 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aarong', '0028_saleproductlist_createdtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='CreatedTime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='OrderCreatedTime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='ShopCreatedTime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
